In [1]:
import numpy as np
import networkx as nx
import generator

def calculate_distance_matrix(G):
    A= nx.adjacency_matrix(G).toarray()
    n_vertices=G.number_of_nodes()
    distance_matrix = np.zeros((n_vertices, n_vertices))


    for i in range(n_vertices):
        for j in range(i + 1, n_vertices):
            A_copy=A.copy()
            euclidean_matrix = (A_copy - A_copy[i,j])**2
            distance_matrix[i, j] = distance_matrix[j, i] = np.sqrt(euclidean_matrix.sum(axis=1)-A_copy[i,j]**2)[i]
    
    return distance_matrix

def find_closest_clusters(distance_matrix):
    np.fill_diagonal(distance_matrix, np.inf)
    return np.unravel_index(np.argmin(distance_matrix, axis=None), distance_matrix.shape)

def hierarchical_clustering(G, n_clusters):
    n_vertices=G.number_of_nodes()
    clusters = [[i] for i in range(n_vertices)]
    distance_matrix = calculate_distance_matrix(G)

    while len(clusters) > n_clusters:
        i, j = find_closest_clusters(distance_matrix)

        new_cluster = clusters[i] + clusters[j]
        clusters.append(new_cluster)

        clusters.pop(max(i, j))
        clusters.pop(min(i, j))

        new_distances = []
        for k in range(len(distance_matrix)):
            if k != i and k != j:
                new_dist = min(distance_matrix[k, i], distance_matrix[k, j])
                new_distances.append(new_dist)
        new_distances.append(0.0)  

        distance_matrix = np.delete(distance_matrix, [max(i, j), min(i, j)], axis=0)
        distance_matrix = np.delete(distance_matrix, [max(i, j), min(i, j)], axis=1)
        new_distances = np.array(new_distances)
        distance_matrix = np.vstack((distance_matrix, new_distances[:-1]))
        distance_matrix = np.column_stack((distance_matrix, new_distances))

    return clusters

# Example usage



In [30]:
pi = np.array([[0.1,1,0.1,0.1],[1,0.1,1,0.1],[0.1,1,0.1,1],[0.1,0.1,1,0.1]])
priors = np.array([0.1, 0.4, 0.4, 0.1])
G=generator.generate(20, pi, priors)

print(G.number_of_edges())
clusters=hierarchical_clustering(G,4)
print(clusters)

99
[[0], [1], [3], [9, 14, 19, 18, 17, 16, 15, 13, 12, 10, 7, 4, 6, 5, 8, 2, 11]]


/var/folders/kk/m7r241y560174wvw5cvj2dfm0000gn/T/ipykernel_50443/1223222977.py:6: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  A= nx.adjacency_matrix(G).toarray()


In [29]:
test_matrix=np.array([[0,1,0,1],[1,0,1,1], [1,1,0,0],[1,1,0,0]])
distance_matrix=np.zeros((4,4))
for i in range(4):
        for j in range(i + 1, 4):
            euclidean_matrix = (test_matrix - test_matrix[i,j])**2
            distance_matrix[i, j] = distance_matrix[j, i] = np.sqrt(euclidean_matrix.sum(axis=1)-test_matrix[i,j]**2)[i]


print(distance_matrix)



[[0.         1.         1.41421356 1.        ]
 [1.         0.         0.         0.        ]
 [1.41421356 0.         0.         1.41421356]
 [1.         0.         1.41421356 0.        ]]


In [2]:
import em

In [4]:
pi = np.array([[0.1,1,0.1,0.1],[1,0.1,1,0.1],[0.1,1,0.1,1],[0.1,0.1,1,0.1]])
priors = np.array([0.1, 0.4, 0.4, 0.1])
G=generator.generate(20, pi, priors)

tau_spectral=em.spectral_clustering(G, 4)
print(tau_spectral)
tau_hierarchical=em.hierarchical_clustering(G,4)
print(tau_hierarchical)

[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
clusters [[2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [0, 1]]
clusters [[3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [2, 0, 1]]
clusters [[5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [2, 0, 1], [3, 4]]
clusters [[7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [2, 0, 1], [3, 4], [5, 6]]
clusters [[8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [3, 4], [5, 6], [7, 2, 0, 1]]
clusters [[9], [11], [12], [13], [14], [15], [16], [17], [18], [19], [3, 4], [5, 6], [7, 2, 0, 1], [8, 10]]
clusters [[11], [12],

/Users/alexandrefrancois/Documents/MVA/Probabilistic graphical models/Code projet/Mixture4graph/em.py:17: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  A = nx.adjacency_matrix(G)
/Users/alexandrefrancois/opt/anaconda3/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/Users/alexandrefrancois/Documents/MVA/Probabilistic graphical models/Code projet/Mixture4graph/em.py:41: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  A= nx.adjacency_matrix(G).toarray()
